spring.application.name=recipeshare
server.port=8081

# This tells the database to save to a file named 'pyroDB' in your project folder
spring.datasource.url=jdbc:h2:file:./data/pyroDB
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# This makes sure the database structure stays the same but keeps your data
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true